import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { doc, onSnapshot, serverTimestamp, updateDoc } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import { auth } from "./auth-shared.js";
import { achEntriesRef, asDate, briefingRef, contactFollowUpsRef, connectionsRef, escapeHtml, financeRef, formatDay, formatDateTime, isOwner, priorityRank, projectsRef, summaryRef, tasksRef } from "./workroom-shared.js";

const $ = (id) => document.getElementById(id);
const elements = {
  gate: $("workroom-display-gate"), gateMessage: $("workroom-display-gate-message"), signIn: $("workroom-display-sign-in"), app: $("workroom-display-app"), clock: $("workroom-clock"), date: $("workroom-date"), completedCount: $("workroom-completed-count"), overdueCount: $("workroom-overdue-count"), overdueStat: $("workroom-overdue-stat"), allCount: $("workroom-all-count"), dayline: $("workroom-dayline-events"), nowReason: $("workroom-now-reason"), nowContent: $("workroom-now-content"), clearPin: $("workroom-clear-pin"), tasks: $("workroom-display-tasks"), radar: $("workroom-radar-list"), radarCounts: $("workroom-radar-counts"), briefingTitle: $("workroom-briefing-title"), briefingPreview: $("workroom-briefing-preview"), briefingUpdated: $("workroom-briefing-updated"), footer: $("workroom-context-footer"), completeToast: $("workroom-complete-toast"), allDialog: $("workroom-all-dialog"), allGroups: $("workroom-all-groups"), briefingDialog: $("workroom-briefing-dialog"), fullBriefing: $("workroom-full-briefing"), openAll: $("workroom-open-all"), viewAll: $("workroom-view-all"), openBriefing: $("workroom-open-briefing"), focusRing: $("workroom-focus-ring"), focusTime: $("workroom-focus-time"), focusLabel: $("workroom-focus-label"), focusStatus: $("workroom-focus-status"), sprintToggle: $("workroom-sprint-toggle"), sprintCancel: $("workroom-sprint-cancel"), sprintChoices: [...document.querySelectorAll("[data-sprint-minutes]")],
};
const PIN_KEY = "workroom-compass-pinned-task";
const SPRINT_KEY = "workroom-compass-sprint";
const QUEUE_LIMIT = 6;
const DAY_MS = 24 * 60 * 60 * 1000;
const quotes = ["Well begun is half done. - Aristotle", "The obstacle is the path. - Zen proverb", "Start where you are. Use what you have. Do what you can. - Arthur Ashe", "The most effective way to do it, is to do it. - Amelia Earhart"];
let state = { user: null, tasks: [], tasksLoaded: false, projects: [], finance: [], contacts: [], ach: [], summary: {}, briefing: {}, connections: [], unsubscribers: [], pinnedTaskId: "", sprint: null, sprintMinutes: 25, activeDialog: null, dialogTrigger: null };
let celebrationTimer = null;

const loadStored = (key, fallback = null) => { try { return JSON.parse(window.localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
const saveStored = (key, value) => { try { if (value == null || value === "") window.localStorage.removeItem(key); else window.localStorage.setItem(key, JSON.stringify(value)); } catch { } };
state.pinnedTaskId = loadStored(PIN_KEY, "");
state.sprint = loadStored(SPRINT_KEY, null);

const removeSubscriptions = () => { state.unsubscribers.forEach((unsubscribe) => unsubscribe()); state.unsubscribers = []; };
const blank = (copy) => `<p class="workroom-tv-empty">${escapeHtml(copy)}</p>`;
const startOfDay = (value = new Date()) => { const date = asDate(value) || new Date(); return new Date(date.getFullYear(), date.getMonth(), date.getDate()); };
const dateKey = (value = new Date()) => { const date = asDate(value); return date ? `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}` : ""; };
const dayOffset = (value, now = new Date()) => { const date = asDate(value); return date ? Math.round((startOfDay(date) - startOfDay(now)) / DAY_MS) : null; };
const relativeDay = (value, now = new Date()) => { const offset = dayOffset(value, now); if (offset == null) return "No date"; if (offset < -1) return `${Math.abs(offset)} days overdue`; if (offset === -1) return "Yesterday"; if (offset === 0) return "Today"; if (offset === 1) return "Tomorrow"; return formatDay(value); };
const dayPhase = (now) => { const minutes = now.getHours() * 60 + now.getMinutes(); if (minutes >= 480 && minutes < 600) return "morning"; if (minutes >= 600 && minutes < 930) return "execution"; if (minutes >= 930 && minutes < 1050) return "wrap"; return "after-hours"; };
const taskBucket = (task, now = new Date()) => { const offset = dayOffset(task.dueDate, now); if (offset != null && offset < 0) return { id: "overdue", label: "Overdue", rank: 0 }; if (offset === 0) return { id: "today", label: "Today", rank: 1 }; if (offset != null && offset <= 7) return { id: "week", label: offset === 1 ? "Tomorrow" : "This week", rank: 2 }; if (offset == null && task.priority === "high") return { id: "high-unscheduled", label: "High priority", rank: 3 }; if (offset != null) return { id: "later", label: "Later", rank: 4 }; return { id: "unscheduled", label: "Unscheduled", rank: 5 }; };
const rankTasks = (tasks, now = new Date()) => [...tasks].sort((left, right) => taskBucket(left, now).rank - taskBucket(right, now).rank || priorityRank(left.priority) - priorityRank(right.priority) || ((asDate(left.dueDate)?.getTime() || Number.MAX_SAFE_INTEGER) - (asDate(right.dueDate)?.getTime() || Number.MAX_SAFE_INTEGER)) || ((asDate(left.createdAt)?.getTime() || 0) - (asDate(right.createdAt)?.getTime() || 0)) || String(left.id).localeCompare(String(right.id)));
const eventDate = (event) => { if (event.allDay && event.date) { const [year, month, day] = String(event.date).split("-").map(Number); return new Date(year, month - 1, day); } return asDate(event.start); };
const eventWhen = (event) => { const date = eventDate(event); if (!date || Number.isNaN(date.getTime())) return "Time unavailable"; if (event.allDay) return "All day"; return new Intl.DateTimeFormat("en-US", { hour: "numeric", minute: "2-digit" }).format(date); };
const parseBriefing = (text) => {
  const sections = { "DO TODAY": [], "THIS WEEK": [], WAITING: [], WATCH: [] };
  let active = "";
  String(text || "").split(/\r?\n/).forEach((line) => { const heading = line.trim().replace(/^#+\s*/, "").replace(/:$/, "").toUpperCase(); if (sections[heading]) { active = heading; return; } if (active && line.trim() && !/^none noted\.?$/i.test(line.trim())) sections[active].push(line.trim().replace(/^[-*]\s*/, "")); });
  return sections;
};
const radarItem = (type, title, detail, time, score, id = "", canComplete = false) => ({ type, title, detail, time, score, id, canComplete });
const deriveRadar = (now) => {
  const items = [];
  state.contacts.filter((item) => item.status !== "done").forEach((item) => { const offset = dayOffset(item.followUpDate, now); const score = offset < 0 ? 0 : offset === 0 ? 2 : offset === 1 ? 5 : 20 + (offset ?? 30); items.push(radarItem("Follow-up", item.name, item.reason, relativeDay(item.followUpDate, now), score, item.id, true)); });
  state.finance.filter((item) => item.status !== "done").forEach((item) => { const offset = dayOffset(item.dueDate, now); const score = offset < 0 ? 0 : offset === 0 ? 2 : offset === 1 ? 5 : 20 + (offset ?? 30); items.push(radarItem("Finance", item.title, item.category || "Reminder", relativeDay(item.dueDate, now), score, item.id, true)); });
  (state.summary.upcomingEvents || []).forEach((event, index) => { const date = eventDate(event); if (!date) return; const minutes = (date - now) / 60000; if (minutes >= -30 && minutes <= 24 * 60) items.push(radarItem("Calendar", event.title, event.location || "Calendar", minutes <= 60 && minutes >= 0 ? `In ${Math.max(1, Math.round(minutes))} min` : eventWhen(event), minutes <= 60 ? 1 : 8 + minutes / 60, `event-${index}`)); });
  state.ach.forEach((item) => { const offset = dayOffset(item.withdrawalDate, now); if (offset != null && offset >= 0 && offset <= 3) items.push(radarItem("ACH", `${item.name} - $${Number(item.amount || 0).toFixed(2)}`, item.reason, relativeDay(item.withdrawalDate, now), 6 + offset, item.id)); });
  state.projects.filter((item) => item.status === "active").forEach((item) => { const offset = dayOffset(item.targetDate, now); if (offset != null && offset <= 7) items.push(radarItem("Project", item.title, "Target date approaching", relativeDay(item.targetDate, now), offset < 0 ? 3 : 12 + offset, item.id)); });
  const unread = Number(state.summary.unreadCount || 0); if (unread) items.push(radarItem("Mail", `${unread} unread message${unread === 1 ? "" : "s"}`, state.summary.recentMail?.[0]?.subject || "Inbox needs a look", "Inbox", 50));
  return items.sort((left, right) => left.score - right.score || left.title.localeCompare(right.title));
};
const deriveDayModel = (now = new Date()) => {
  const openTasks = rankTasks(state.tasks.filter((task) => task.status !== "done"), now);
  const pinned = openTasks.find((task) => task.id === state.pinnedTaskId);
  if (state.tasksLoaded && state.pinnedTaskId && !pinned) { state.pinnedTaskId = ""; saveStored(PIN_KEY, null); }
  const current = pinned || openTasks[0] || null;
  const queued = openTasks.filter((task) => task.id !== current?.id);
  const completedToday = state.tasks.filter((task) => task.status === "done" && dateKey(task.completedAt) === dateKey(now));
  const events = (state.summary.upcomingEvents || []).map((event) => ({ ...event, startDate: eventDate(event) })).filter((event) => event.startDate && dayOffset(event.startDate, now) === 0).sort((left, right) => left.startDate - right.startDate);
  return { now, phase: dayPhase(now), openTasks, current, queued, completedToday, overdueCount: openTasks.filter((task) => taskBucket(task, now).id === "overdue").length, events, radar: deriveRadar(now), briefingSections: parseBriefing(state.briefing.text), briefingStale: Boolean(state.briefing.text) && state.briefing.dateKey !== dateKey(now), tomorrowCount: openTasks.filter((task) => dayOffset(task.dueDate, now) === 1).length };
};

const projectName = (task) => state.projects.find((project) => project.id === task?.projectId)?.title || "";
const completeButton = (type, item, label = item.title || item.name) => `<button class="workroom-display-check" data-complete-${type}="${escapeHtml(item.id)}" type="button" aria-label="Complete ${escapeHtml(label)}"></button>`;
const taskRow = (task, now) => { const bucket = taskBucket(task, now); const project = projectName(task); return `<div class="workroom-compass-task priority-${escapeHtml(task.priority)}"><button class="workroom-task-select" data-pin-task="${escapeHtml(task.id)}" type="button"><span class="workroom-task-title">${escapeHtml(task.title)}</span><small><span class="workroom-status-label status-${bucket.id}">${escapeHtml(bucket.label)}</span>${project ? ` <span>${escapeHtml(project)}</span>` : ""}${task.dueDate ? ` <span>${escapeHtml(formatDay(task.dueDate))}</span>` : ""}</small></button>${completeButton("task", task)}</div>`; };
const renderDayline = (model) => { if (!model.events.length) { elements.dayline.innerHTML = `<span class="workroom-dayline-clear">Open runway - no calendar events today.</span>`; return; } const next = model.events.find((event) => !event.allDay && (event.startDate - model.now) / 60000 >= -30); elements.dayline.innerHTML = model.events.slice(0, 5).map((event) => { const minutes = (event.startDate - model.now) / 60000; const elapsed = !event.allDay && minutes < -30; const isNext = event === next; const countdown = isNext && minutes >= 0 && minutes <= 60 ? `In ${Math.max(1, Math.round(minutes))} min` : eventWhen(event); return `<div class="workroom-dayline-event ${elapsed ? "is-elapsed" : ""} ${isNext ? "is-next" : ""}"><time>${escapeHtml(countdown)}</time><strong>${escapeHtml(event.title)}</strong></div>`; }).join(""); };
const renderNow = (model) => { const task = model.current; elements.clearPin.hidden = !state.pinnedTaskId; elements.nowReason.textContent = task ? (state.pinnedTaskId ? "Pinned focus" : taskBucket(task, model.now).label) : "Queue clear"; elements.nowContent.innerHTML = task ? `<div class="workroom-now-task"><div><span class="workroom-now-project">${escapeHtml(projectName(task) || "Independent task")}</span><h1>${escapeHtml(task.title)}</h1><p>${task.notes ? escapeHtml(task.notes) : task.dueDate ? `${escapeHtml(relativeDay(task.dueDate, model.now))} - ${escapeHtml(formatDay(task.dueDate))}` : "No due date - ready when you are."}</p></div>${completeButton("task", task)}</div>` : `<div class="workroom-now-empty"><h1>All clear.</h1><p>Nothing open is asking for your attention.</p></div>`; };
const renderQueue = (model) => { elements.tasks.innerHTML = model.queued.length ? model.queued.slice(0, QUEUE_LIMIT).map((task) => taskRow(task, model.now)).join("") : blank(model.current ? "This is the only open task." : "The queue is clear."); const remaining = Math.max(0, model.queued.length - QUEUE_LIMIT); elements.viewAll.textContent = remaining ? `View all +${remaining}` : "View all"; elements.viewAll.hidden = !model.openTasks.length; };
const renderRadar = (model) => { elements.radar.innerHTML = model.radar.length ? model.radar.slice(0, 4).map((item) => `<div class="workroom-radar-item radar-${item.score <= 3 ? "urgent" : "normal"}"><div><span>${escapeHtml(item.type)}</span><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.time)}${item.detail ? ` - ${escapeHtml(item.detail)}` : ""}</small></div>${item.canComplete ? completeButton(item.type === "Finance" ? "finance" : "contact", item) : ""}</div>`).join("") : blank("Nothing else needs attention right now."); const counts = [{ label: "Follow-ups", value: state.contacts.filter((item) => item.status !== "done").length }, { label: "Finance", value: state.finance.filter((item) => item.status !== "done").length }, { label: "ACH", value: state.ach.filter((item) => (dayOffset(item.withdrawalDate, model.now) ?? -1) >= 0).length }, { label: "Mail", value: Number(state.summary.unreadCount || 0) }]; elements.radarCounts.innerHTML = counts.map((item) => `<span><strong>${item.value}</strong>${escapeHtml(item.label)}</span>`).join(""); };
const renderBriefing = (model) => { const today = model.briefingSections["DO TODAY"]; const waiting = model.briefingSections.WAITING; const failed = state.briefing.status === "error"; elements.briefingTitle.textContent = failed ? "Briefing unavailable" : model.briefingStale ? "Briefing needs refresh" : "Do today"; const lines = [...today.slice(0, 2), ...waiting.slice(0, 1).map((line) => `Waiting: ${line}`)]; elements.briefingPreview.innerHTML = failed ? blank(state.briefing.error || "The latest briefing could not be generated.") : lines.length ? lines.map((line) => `<p>${escapeHtml(line)}</p>`).join("") : blank(state.briefing.text ? "No immediate items noted." : "Generate a briefing from the control room."); elements.briefingUpdated.textContent = failed ? "Run a new review from the control room." : state.briefing.generatedAt ? `${model.briefingStale ? "Stale - " : ""}Updated ${formatDateTime(state.briefing.generatedAt)}` : "Waiting for the first briefing."; elements.fullBriefing.innerHTML = (failed ? `<p class="workroom-briefing-error">${escapeHtml(state.briefing.error || "The latest briefing could not be generated.")}</p>` : "") + Object.entries(model.briefingSections).map(([heading, items]) => `<section><h3>${escapeHtml(heading)}</h3>${items.length ? items.map((item) => `<p>${escapeHtml(item)}</p>`).join("") : `<p class="workroom-tv-empty">None noted.</p>`}</section>`).join("") + (state.briefing.sourceCounts ? `<p class="workroom-briefing-receipt">Reviewed ${Number(state.briefing.sourceCounts.tasks || 0)} tasks, ${Number(state.briefing.sourceCounts.calendarEvents || 0)} events, ${Number(state.briefing.sourceCounts.recentMail || 0)} mail messages, and ${Number(state.briefing.sourceCounts.slackMessages || 0)} Slack messages.</p>` : ""); };
const renderAllWork = (model) => { const groups = [{ id: "overdue", title: "Overdue" }, { id: "today", title: "Today" }, { id: "week", title: "This week" }, { id: "high-unscheduled", title: "High priority" }, { id: "later", title: "Later" }, { id: "unscheduled", title: "Unscheduled" }]; elements.allGroups.innerHTML = groups.map((group) => { const tasks = model.openTasks.filter((task) => taskBucket(task, model.now).id === group.id); return tasks.length ? `<section><h3>${group.title} <span>${tasks.length}</span></h3>${tasks.map((task) => taskRow(task, model.now)).join("")}</section>` : ""; }).join("") + (model.completedToday.length ? `<section><h3>Finished today <span>${model.completedToday.length}</span></h3>${model.completedToday.map((task) => `<div class="workroom-finished-task">${escapeHtml(task.title)}</div>`).join("")}</section>` : ""); };
const renderFooter = (model) => { if (!model.openTasks.length) elements.footer.textContent = `${model.completedToday.length} finished today. The room is clear.`; else if (model.phase === "wrap") elements.footer.textContent = `${model.completedToday.length} finished today - ${model.tomorrowCount} due tomorrow.`; else if (model.overdueCount) elements.footer.textContent = `${model.overdueCount} overdue item${model.overdueCount === 1 ? "" : "s"}. Clear the oldest promise first.`; else elements.footer.textContent = quotes[new Date().getDate() % quotes.length]; };
const renderSprint = (now = Date.now()) => { const task = state.tasks.find((item) => item.id === state.sprint?.taskId && item.status !== "done"); if (state.tasksLoaded && state.sprint && !task) { state.sprint = null; saveStored(SPRINT_KEY, null); document.title = "The Workroom"; } const sprint = state.sprint; let remaining = state.sprintMinutes * 60 * 1000; let progress = 0; if (sprint) { remaining = sprint.running ? Math.max(0, sprint.endAt - now) : sprint.remainingMs; progress = 1 - remaining / sprint.durationMs; if (remaining <= 0 && sprint.running) { sprint.running = false; sprint.remainingMs = 0; document.title = "Focus complete - The Workroom"; saveStored(SPRINT_KEY, sprint); } } const minutes = Math.floor(remaining / 60000); const seconds = Math.floor((remaining % 60000) / 1000); elements.focusTime.textContent = `${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`; elements.focusRing.style.setProperty("--focus-progress", `${Math.max(0, Math.min(1, progress)) * 360}deg`); elements.focusLabel.textContent = sprint ? task?.title || "Focus sprint" : "Focus sprint"; elements.focusStatus.textContent = !sprint ? "Choose a quiet block for this task." : remaining <= 0 ? "Sprint complete. Take a breath." : sprint.running ? "In progress" : "Paused"; elements.sprintToggle.disabled = !deriveDayModel().current; elements.sprintToggle.textContent = !sprint ? "Start" : sprint.running ? "Pause" : remaining <= 0 ? "Restart" : "Resume"; elements.sprintCancel.hidden = !sprint; elements.sprintChoices.forEach((button) => button.classList.toggle("is-active", Number(button.dataset.sprintMinutes) === state.sprintMinutes)); };
const render = () => { const model = deriveDayModel(); document.body.dataset.dayPhase = model.phase; elements.completedCount.textContent = String(model.completedToday.length); elements.overdueCount.textContent = String(model.overdueCount); elements.overdueStat.classList.toggle("is-urgent", model.overdueCount > 0); elements.allCount.textContent = String(model.openTasks.length); renderDayline(model); renderNow(model); renderQueue(model); renderRadar(model); renderBriefing(model); renderAllWork(model); renderFooter(model); renderSprint(); };

const celebrate = (message) => { elements.completeToast.textContent = message; elements.completeToast.classList.add("is-visible"); window.clearTimeout(celebrationTimer); celebrationTimer = window.setTimeout(() => elements.completeToast.classList.remove("is-visible"), 2400); };
const writeCompletion = async (type, id) => { const collection = type === "task" ? tasksRef : type === "finance" ? financeRef : contactFollowUpsRef; const item = (type === "task" ? state.tasks : type === "finance" ? state.finance : state.contacts).find((entry) => entry.id === id); if (!item || !state.user) return; await updateDoc(doc(collection(state.user.uid), id), { status: "done", completedAt: serverTimestamp(), updatedAt: serverTimestamp() }); if (type === "task" && state.pinnedTaskId === id) { state.pinnedTaskId = ""; saveStored(PIN_KEY, null); } if (type === "task" && state.sprint?.taskId === id) { state.sprint = null; saveStored(SPRINT_KEY, null); document.title = "The Workroom"; } };
const openDialog = (dialog, trigger) => { state.activeDialog = dialog; state.dialogTrigger = trigger; dialog.hidden = false; document.body.classList.add("workroom-dialog-open"); dialog.querySelector(".workroom-dialog-close")?.focus(); };
const closeDialog = () => { if (!state.activeDialog) return; state.activeDialog.hidden = true; document.body.classList.remove("workroom-dialog-open"); state.dialogTrigger?.focus(); state.activeDialog = null; state.dialogTrigger = null; };
const toggleSprint = () => { const current = deriveDayModel().current; if (!current) return; if (!state.sprint || state.sprint.remainingMs <= 0 || state.sprint.taskId !== current.id) { const durationMs = state.sprintMinutes * 60 * 1000; state.sprint = { taskId: current.id, durationMs, remainingMs: durationMs, endAt: Date.now() + durationMs, running: true }; state.pinnedTaskId = current.id; saveStored(PIN_KEY, current.id); } else if (state.sprint.running) { state.sprint.remainingMs = Math.max(0, state.sprint.endAt - Date.now()); state.sprint.running = false; } else { state.sprint.endAt = Date.now() + state.sprint.remainingMs; state.sprint.running = true; } saveStored(SPRINT_KEY, state.sprint); render(); };

document.addEventListener("click", async (event) => {
  const pin = event.target.closest("[data-pin-task]"); if (pin) { if (state.sprint?.taskId && state.sprint.taskId !== pin.dataset.pinTask) { state.sprint = null; saveStored(SPRINT_KEY, null); document.title = "The Workroom"; } state.pinnedTaskId = pin.dataset.pinTask; saveStored(PIN_KEY, state.pinnedTaskId); closeDialog(); render(); return; }
  if (event.target.closest("#workroom-clear-pin")) { if (state.sprint?.taskId === state.pinnedTaskId) { state.sprint = null; saveStored(SPRINT_KEY, null); document.title = "The Workroom"; } state.pinnedTaskId = ""; saveStored(PIN_KEY, null); render(); return; }
  if (event.target.closest("#workroom-open-all, #workroom-view-all")) { openDialog(elements.allDialog, event.target.closest("button")); return; }
  if (event.target.closest("#workroom-open-briefing, [data-open-briefing]")) { openDialog(elements.briefingDialog, event.target.closest("button")); return; }
  if (event.target.closest("[data-close-display-dialog]")) { closeDialog(); return; }
  const sprintChoice = event.target.closest("[data-sprint-minutes]"); if (sprintChoice) { state.sprintMinutes = Number(sprintChoice.dataset.sprintMinutes); if (!state.sprint) renderSprint(); return; }
  if (event.target.closest("#workroom-sprint-toggle")) { toggleSprint(); return; }
  if (event.target.closest("#workroom-sprint-cancel")) { state.sprint = null; saveStored(SPRINT_KEY, null); document.title = "The Workroom"; render(); return; }
  const complete = event.target.closest("[data-complete-task], [data-complete-contact], [data-complete-finance]"); if (!complete) return;
  const type = complete.dataset.completeTask ? "task" : complete.dataset.completeFinance ? "finance" : "contact"; const id = complete.dataset.completeTask || complete.dataset.completeFinance || complete.dataset.completeContact;
  complete.disabled = true; try { await writeCompletion(type, id); celebrate("Done - nice work."); } catch { celebrate("Could not update that item."); complete.disabled = false; }
});
document.addEventListener("keydown", (event) => {
  if (event.key === "Escape") { closeDialog(); return; }
  if (event.key !== "Tab" || !state.activeDialog) return;
  const focusable = [...state.activeDialog.querySelectorAll("button:not([disabled]), [href], [tabindex]:not([tabindex='-1'])")];
  if (!focusable.length) return;
  const first = focusable[0]; const last = focusable[focusable.length - 1];
  if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
  else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
});
const tick = () => { const now = new Date(); elements.clock.textContent = new Intl.DateTimeFormat("en-US", { hour: "numeric", minute: "2-digit" }).format(now); elements.date.textContent = new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric" }).format(now); renderSprint(now.getTime()); };
tick(); window.setInterval(tick, 1000); window.setInterval(() => { if (state.user) render(); }, 60_000);

onAuthStateChanged(auth, (user) => {
  removeSubscriptions(); state.user = user;
  if (!user || !isOwner(user)) { elements.app.classList.add("hidden"); elements.gate.classList.remove("hidden"); elements.signIn.classList.toggle("hidden", Boolean(user)); elements.gateMessage.textContent = user ? "This private display is reserved for its owner." : "Sign in with the Workroom owner account to view the dashboard."; return; }
  elements.gate.classList.add("hidden"); elements.app.classList.remove("hidden");
  state.unsubscribers.push(
    onSnapshot(tasksRef(user.uid), (snapshot) => { state.tasks = snapshot.docs.map((item) => ({ id: item.id, ...item.data() })); state.tasksLoaded = true; render(); }),
    onSnapshot(projectsRef(user.uid), (snapshot) => { state.projects = snapshot.docs.map((item) => ({ id: item.id, ...item.data() })); render(); }),
    onSnapshot(financeRef(user.uid), (snapshot) => { state.finance = snapshot.docs.map((item) => ({ id: item.id, ...item.data() })); render(); }),
    onSnapshot(contactFollowUpsRef(user.uid), (snapshot) => { state.contacts = snapshot.docs.map((item) => ({ id: item.id, ...item.data() })); render(); }),
    onSnapshot(achEntriesRef(user.uid), (snapshot) => { state.ach = snapshot.docs.map((item) => ({ id: item.id, ...item.data() })); render(); }),
    onSnapshot(summaryRef(user.uid), (snapshot) => { state.summary = snapshot.data() || {}; render(); }),
    onSnapshot(briefingRef(user.uid), (snapshot) => { state.briefing = snapshot.data() || {}; render(); }),
    onSnapshot(connectionsRef(user.uid), (snapshot) => { state.connections = snapshot.docs.map((item) => item.data()); render(); }),
  );
});